// Pre-authentication credentials.
//
// This is what a browser holds between "the password was right" and "the second
// factor was right". It is a bearer credential carrying a completed password
// proof, so it gets exactly the discipline sessions get: high entropy, raw in
// the cookie, digest in the database, and a domain of its own.
//
// A FIFTH digest domain. Verification codes, reset tokens, session tokens,
// recovery codes and now this — five credentials that would all digest
// identically without their prefixes, and each of which would then be
// presentable as the others (§1, INV-292).

import { randomBytes, createHash } from "node:crypto";
import type { PendingAuthDigest } from "@lagda/application";

/** 32 bytes, base64url — the same 256 bits a session token carries. */
const TOKEN_BYTES = 32;
const ENCODED_LENGTH = 43;

/**
 * Sized like a session token, not like an OTP.
 *
 * This credential is generated by the server and handled by the browser, never
 * typed by a person, so there is no reason to trade entropy for legibility —
 * and stealing one means inheriting somebody's password proof.
 */
const DIGEST_DOMAIN = "lagda.pre-auth";

const TOKEN_PATTERN = /^[A-Za-z0-9_-]+$/;

export function digestPreAuthToken(token: string): PendingAuthDigest {
  return createHash("sha256")
    .update(`${DIGEST_DOMAIN}:${token}`)
    .digest("hex") as PendingAuthDigest;
}

export function isWellFormedPreAuthToken(raw: string): boolean {
  return raw.length === ENCODED_LENGTH && TOKEN_PATTERN.test(raw);
}

export function digestSubmittedPreAuthToken(raw: string): PendingAuthDigest | null {
  return isWellFormedPreAuthToken(raw) ? digestPreAuthToken(raw) : null;
}

export function createPreAuthCredentialFactory(): {
  readonly issue: () => { readonly raw: string; readonly digest: PendingAuthDigest };
  readonly digestSubmitted: (raw: string) => PendingAuthDigest | null;
} {
  return {
    issue() {
      const raw = randomBytes(TOKEN_BYTES).toString("base64url");
      // The RAW value goes into an httpOnly cookie and nowhere else. Never
      // persisted, never logged, never in a JSON body (§52, §216).
      return { raw, digest: digestPreAuthToken(raw) };
    },
    digestSubmitted: digestSubmittedPreAuthToken,
  };
}
