// The document sealing seam.
//
// BACKEND-00 built the architecture around this boundary: one high-level
// operation, so a future Java or .NET signer replaces the implementation
// without any caller changing. Everything here is LAGDA-owned — no `pdf-lib`
// type, no Node `Buffer`, no storage handle, no database row.
//
// THREE seams now live in `@lagda/sealing`, each with exactly one caller in the
// completion pipeline: `DocumentSealer` (this file), `FieldMerger` (BACKEND-39,
// below) and `CompletionCertificateGenerator` (BACKEND-40, in
// `completion-certificate.ts`). They are separate interfaces rather than methods
// on one, so a remote signing service replacing `DocumentSealer` does not also
// have to implement field rendering and certificate layout — which stay local.
//
// `hashDocument` remains a private collaborator and is not exposed: a caller
// able to hash without sealing, or seal without hashing, is what INV-002 exists
// to prevent.

import type { WorkspaceId, DocumentId, TransactionId, Sha256Digest, VerificationId } from "@lagda/contracts";

// ── Binary documents ─────────────────────────────────────────────────────────

/**
 * Document bytes.
 *
 * `Uint8Array`, not Node's `Buffer`. `Buffer` is a Node-only type, and putting
 * it in the seam would mean a remote signer implemented in another runtime
 * could not satisfy the same contract. The Node adapter converts internally.
 */
export type DocumentBytes = Uint8Array;

// ── Fields ───────────────────────────────────────────────────────────────────

/**
 * Field types the sealer can render.
 *
 * Only what the product actually has. No radio, attachment, formula, payment or
 * notary seal — inventing rendering for a field type nobody can create produces
 * untested code that looks supported.
 */
export const SEALABLE_FIELD_TYPES = [
  "signature", "initials", "text", "date", "checkbox",
] as const;
export type SealableFieldType = (typeof SEALABLE_FIELD_TYPES)[number];

/**
 * Where a field sits, in the frontend's normalized coordinate space.
 *
 * **Origin is TOP-LEFT**, values are 0–1 of the page. PDF's native origin is
 * BOTTOM-LEFT, so the adapter flips the Y axis. That conversion happens in
 * exactly one place — see `docs/backend/sealing/PDF_COORDINATE_MODEL.md`.
 * Duplicating it across layers is how a signature ends up upside down on one
 * path and correct on another.
 */
export interface NormalizedFieldRect {
  /** 0–1 from the LEFT edge. */
  readonly x: number;
  /** 0–1 from the TOP edge. */
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

/**
 * `SealableField` is GONE — OD-162, closed by BACKEND-39.
 *
 * `seal()` used to take completed field values and render them. It no longer
 * does: the `field-merge` step renders them and produces a `merged-candidate`
 * artifact, and `seal()` receives that already-rendered document.
 *
 * Leaving the parameter in place would have been worse than removing it. Once
 * `field-merge` renders the fields, a `seal()` that still renders them draws
 * every value a SECOND time, one drawn over the other — and that reads as a
 * font-weight or double-strike bug, not as an architecture bug. Nobody would
 * look here.
 *
 * The renderable-type vocabulary above stays: `renderTypeFor` in
 * `@lagda/core` collapses the product's nine preparation field types onto it,
 * and that mapping is unaffected by which component does the drawing.
 */
export type SealableFieldRemoved = never;

/**
 * `CompletionEvidence` and `CertificateParticipant` are GONE — OD-167.
 *
 * They existed so `seal()` could render the certificate. BACKEND-40 owns the
 * certificate now, and its curated model lives in `completion-certificate.ts`
 * where it can carry authentication, consent and ceremony facts these shapes
 * never had.
 *
 * Removed rather than left unread: a field nobody consumes is an invitation for
 * the next implementer to start consuming it, and this one would have handed
 * the sealer a second, weaker view of the same evidence.
 */
export type CompletionEvidenceRemoved = never;

// ── Request ──────────────────────────────────────────────────────────────────

export interface SealRequest {
  readonly workspaceId: WorkspaceId;
  readonly transactionId: TransactionId;
  readonly documentId: DocumentId;

  /**
   * The document to seal, with every field value ALREADY RENDERED.
   *
   * This is the `merged-candidate` the `field-merge` step produced, not the
   * prepared document. Supplied by the caller — the sealer never fetches from
   * object storage, so a future remote signer needs no knowledge of LAGDA's
   * storage topology.
   *
   * The name is kept because `preparedDocumentHash` in the result is a
   * published digest: renaming the field without renaming the hash would make
   * the pair disagree, and renaming the hash changes what a verification page
   * compares against.
   */
  readonly preparedDocument: DocumentBytes;

  /**
   * Generated by the APPLICATION, not the sealer.
   *
   * The specified format is `LAGDA-{workspace}-{date}-{random}`. Randomness and
   * identity belong to the application layer — a sealer that minted business
   * identifiers would be non-deterministic, and a future remote signer would
   * own LAGDA's verification namespace, which it must not.
   */
  readonly verificationId: VerificationId;

  /** Supplied so output is reproducible and never depends on a hidden clock. */
  readonly sealedAt: string;
}

// ── Seal metadata ────────────────────────────────────────────────────────────

/**
 * How a sealed artifact was produced, recorded from the first record written.
 *
 * A discriminated union rather than an untyped bag: `sealScheme` is the
 * discriminant, so a record produced under one scheme stays interpretable after
 * another is introduced. Only the current variant exists — a speculative
 * certificate variant would be fields nobody writes.
 */
export interface HashEvidenceSealMetadata {
  readonly sealScheme: "hash-evidence";
  /**
   * The version of LAGDA's SEALING PROCEDURE — not an API version, not a
   * package version, not a document version. It increments when a change alters
   * how existing sealed artifacts must be interpreted.
   */
  readonly sealVersion: 1;
  readonly digestAlgorithm: "sha-256";
}

export type SealMetadata = HashEvidenceSealMetadata;

// ── Result ───────────────────────────────────────────────────────────────────

export interface SealResult {
  /** The final distributed document, fields rendered. A NEW artifact. */
  readonly sealedDocument: DocumentBytes;

  /**
   * `completionCertificate` is GONE — OD-167, the twin of OD-162.
   *
   * `seal()` used to render the certificate as well. BACKEND-40's CERTIFICATE
   * step produces it as its own immutable artifact, so a `seal()` that still
   * returned one would hand completion TWO certificates with no way to tell
   * which was authoritative. Handoff §15 still stores three artifacts; they are
   * now produced by three steps.
   */

  /** Digest of `preparedDocument` exactly as received. */
  readonly preparedDocumentHash: Sha256Digest;

  /**
   * Digest of `sealedDocument` — the exact bytes distributed.
   *
   * Computed AFTER every byte-changing step. Hashing before a later
   * modification and publishing that digest as final would make verification
   * fail against the document people actually hold.
   */
  readonly signedDocumentHash: Sha256Digest;

  /** Echoed back, not generated here. */
  readonly verificationId: VerificationId;

  readonly seal: SealMetadata;
}

/**
 * The one operation.
 *
 * Implemented today by `NodeDocumentSealer`. A `RemoteDocumentSealer` calling a
 * Java or .NET service would implement this same interface, and no caller would
 * change.
 */
export interface DocumentSealer {
  seal(request: SealRequest): Promise<SealResult>;
}

// ── Field merge (BACKEND-39) ─────────────────────────────────────────────────
//
// A SECOND seam, deliberately not a second method on `DocumentSealer`.
//
// The completion pipeline's `field-merge` step must produce a durable
// `merged-candidate` artifact WITHOUT invoking the sealer, and `DocumentSealer`
// is the one-operation boundary a remote signer replaces wholesale. Hanging
// `mergeFields` off it would mean a remote signing service had to implement
// field rendering to satisfy the interface — which is exactly backwards, since
// merging is the part that stays local.
//
// So: one package, two seams, one caller each. An architecture guard asserts
// `DocumentSealer` still declares exactly one method.
//
// **`seal()` still merges fields today (OD-162).** BACKEND-41 must narrow it
// when it wires this step in, or every field renders twice — and it will look
// like a font-weight bug rather than an architecture bug.

/**
 * A typed signature: text the signer entered, in one of FOUR server-known
 * styles.
 *
 * `styleIndex` selects the style. A client cannot name a font, a family or a
 * stylesheet — §60 — because there is nowhere in this shape to put one.
 */
export interface TypedSignatureRepresentation {
  readonly kind: "typed";
  readonly text: string;
  /** 0–3. Any other value is refused by the renderer, not clamped. */
  readonly styleIndex: number;
}

/**
 * A drawn signature: the raster the signer produced on the canvas.
 *
 * **This is the case the pre-BACKEND-39 renderer could not draw at all.** It
 * rendered `signature` fields with `drawText` in an oblique face — a typed
 * rendering — and a raster has no text to draw, so a drawn signature produced
 * nothing.
 *
 * Bytes are DECODED. Never a data URL and never base64: the
 * `data:image/png;base64,` prefix is transport formatting and is not evidence
 * of anything (§199).
 */
export interface RasterSignatureRepresentation {
  readonly kind: "raster";
  readonly bytes: DocumentBytes;
  /** `image/png`. The product's canvas emits nothing else, and §52 verifies it. */
  readonly mediaType: string;
  /** The raster's own pixel dimensions, used to preserve aspect ratio. */
  readonly width: number;
  readonly height: number;
}

export type SignatureRepresentation =
  | TypedSignatureRepresentation
  | RasterSignatureRepresentation;

/**
 * What a field renders.
 *
 * A discriminated union rather than one `value: string`, because a raster
 * signature is not a string and encoding it as one is how a drawn signature
 * silently became a typed one. The checkbox carries a `boolean` for the same
 * reason: `"false"` and `"FALSE"` and `""` are three strings and one intent.
 */
export type MergeableFieldValue =
  | { readonly kind: "text"; readonly text: string }
  | { readonly kind: "checkbox"; readonly checked: boolean }
  | { readonly kind: "signature"; readonly representation: SignatureRepresentation };

export interface MergeableField {
  /**
   * Identity, carried so rendering order is DETERMINISTIC and so a placement
   * error can name the field without naming its value.
   */
  readonly fieldId: string;
  /** **1-based**, matching the product. The adapter converts to pdf-lib's index. */
  readonly pageNumber: number;
  readonly rect: NormalizedFieldRect;
  readonly value: MergeableFieldValue;
}

export interface MergeFieldsRequest {
  /**
   * The EXACT bytes the signing request froze — its `sourceArtifactId`, not the
   * document's current artifact. Supplied by the caller; the merger never
   * fetches from storage.
   */
  readonly sourceDocument: DocumentBytes;
  readonly fields: readonly MergeableField[];
  /** Supplied so output is reproducible and never depends on a hidden clock. */
  readonly mergedAt: string;
}

export interface MergeFieldsResult {
  /**
   * The merged candidate. Fields rendered, NOT sealed.
   *
   * Named for what it is — §8 and §81 both forbid calling it final. It becomes
   * the input to the certificate and final-seal steps.
   */
  readonly mergedDocument: DocumentBytes;
  /** Digest of `sourceDocument` exactly as received, before anything touched it. */
  readonly sourceDocumentHash: Sha256Digest;
  /** Digest of `mergedDocument` — computed after every byte-changing step. */
  readonly mergedDocumentHash: Sha256Digest;
  /** How many fields were drawn. The caller checks it against what it sent. */
  readonly renderedFieldCount: number;
}

/**
 * Renders accepted values onto the source document.
 *
 * Never calls `DocumentSealer`, never touches storage, never reads a clock.
 */
export interface FieldMerger {
  mergeFields(request: MergeFieldsRequest): Promise<MergeFieldsResult>;
}
