// The document sealing seam.
//
// BACKEND-00 built the architecture around this boundary: one high-level
// operation, so a future Java or .NET signer replaces the implementation
// without any caller changing. Everything here is LAGDA-owned — no `pdf-lib`
// type, no Node `Buffer`, no storage handle, no database row.
//
// The seam is `seal()`. `mergeFields`, `hashDocument` and `renderCertificate`
// exist inside `@lagda/sealing` as private collaborators; exposing them would
// give twenty callers a reason to reach past the boundary, and INV-002 exists
// so exactly one does.

import type { WorkspaceId, DocumentId, TransactionId, Sha256Digest, VerificationId } from "@lagda/contracts";

// ── Binary documents ─────────────────────────────────────────────────────────

/**
 * Document bytes.
 *
 * `Uint8Array`, not Node's `Buffer`. `Buffer` is a Node-only type, and putting
 * it in the seam would mean a remote signer implemented in another runtime
 * could not satisfy the same contract. The Node adapter converts internally.
 */
export type DocumentBytes = Uint8Array;

// ── Fields ───────────────────────────────────────────────────────────────────

/**
 * Field types the sealer can render.
 *
 * Only what the product actually has. No radio, attachment, formula, payment or
 * notary seal — inventing rendering for a field type nobody can create produces
 * untested code that looks supported.
 */
export const SEALABLE_FIELD_TYPES = [
  "signature", "initials", "text", "date", "checkbox",
] as const;
export type SealableFieldType = (typeof SEALABLE_FIELD_TYPES)[number];

/**
 * Where a field sits, in the frontend's normalized coordinate space.
 *
 * **Origin is TOP-LEFT**, values are 0–1 of the page. PDF's native origin is
 * BOTTOM-LEFT, so the adapter flips the Y axis. That conversion happens in
 * exactly one place — see `docs/backend/sealing/PDF_COORDINATE_MODEL.md`.
 * Duplicating it across layers is how a signature ends up upside down on one
 * path and correct on another.
 */
export interface NormalizedFieldRect {
  /** 0–1 from the LEFT edge. */
  readonly x: number;
  /** 0–1 from the TOP edge. */
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

/**
 * A completed field, ready to render.
 *
 * The value is authoritative and comes from the completion pipeline. The sealer
 * renders what it is given and never invents an answer — a `date` field shows
 * the value the signer submitted, not today's server date.
 */
export interface SealableField {
  readonly type: SealableFieldType;
  /** **1-based**, matching the product. The adapter converts to pdf-lib's 0-based index. */
  readonly pageNumber: number;
  readonly rect: NormalizedFieldRect;
  /** Rendered text, or the checkbox state as `"true"`/`"false"`. */
  readonly value: string;
}

// ── Evidence for the completion certificate ──────────────────────────────────

/**
 * What appears on the completion certificate.
 *
 * A **projection** of internal evidence, not the whole record. The certificate
 * ships with the document to every participant, so it carries who acted and
 * when — and deliberately not IP addresses, device fingerprints or precise
 * location, none of which the current specification asks to show and all of
 * which would be handed to every recipient.
 */
export interface CertificateParticipant {
  readonly name: string;
  readonly action: string;
  readonly completedAt: string;
}

export interface CompletionEvidence {
  readonly documentName: string;
  readonly completedAt: string;
  readonly participants: readonly CertificateParticipant[];
}

// ── Request ──────────────────────────────────────────────────────────────────

export interface SealRequest {
  readonly workspaceId: WorkspaceId;
  readonly transactionId: TransactionId;
  readonly documentId: DocumentId;

  /**
   * The prepared document. Supplied by the caller — the sealer never fetches
   * from object storage, so a future remote signer needs no knowledge of
   * LAGDA's storage topology.
   */
  readonly preparedDocument: DocumentBytes;

  readonly fields: readonly SealableField[];
  readonly evidence: CompletionEvidence;

  /**
   * Generated by the APPLICATION, not the sealer.
   *
   * The specified format is `LAGDA-{workspace}-{date}-{random}`. Randomness and
   * identity belong to the application layer — a sealer that minted business
   * identifiers would be non-deterministic, and a future remote signer would
   * own LAGDA's verification namespace, which it must not.
   */
  readonly verificationId: VerificationId;

  /** Supplied so output is reproducible and never depends on a hidden clock. */
  readonly sealedAt: string;
}

// ── Seal metadata ────────────────────────────────────────────────────────────

/**
 * How a sealed artifact was produced, recorded from the first record written.
 *
 * A discriminated union rather than an untyped bag: `sealScheme` is the
 * discriminant, so a record produced under one scheme stays interpretable after
 * another is introduced. Only the current variant exists — a speculative
 * certificate variant would be fields nobody writes.
 */
export interface HashEvidenceSealMetadata {
  readonly sealScheme: "hash-evidence";
  /**
   * The version of LAGDA's SEALING PROCEDURE — not an API version, not a
   * package version, not a document version. It increments when a change alters
   * how existing sealed artifacts must be interpreted.
   */
  readonly sealVersion: 1;
  readonly digestAlgorithm: "sha-256";
}

export type SealMetadata = HashEvidenceSealMetadata;

// ── Result ───────────────────────────────────────────────────────────────────

export interface SealResult {
  /** The final distributed document, fields rendered. A NEW artifact. */
  readonly sealedDocument: DocumentBytes;

  /**
   * A separate artifact, not appended — handoff §15 stores "original PDF +
   * signed PDF + completion certificate" as three things.
   */
  readonly completionCertificate: DocumentBytes;

  /** Digest of `preparedDocument` exactly as received. */
  readonly preparedDocumentHash: Sha256Digest;

  /**
   * Digest of `sealedDocument` — the exact bytes distributed.
   *
   * Computed AFTER every byte-changing step. Hashing before a later
   * modification and publishing that digest as final would make verification
   * fail against the document people actually hold.
   */
  readonly signedDocumentHash: Sha256Digest;

  /** Echoed back, not generated here. */
  readonly verificationId: VerificationId;

  readonly seal: SealMetadata;
}

/**
 * The one operation.
 *
 * Implemented today by `NodeDocumentSealer`. A `RemoteDocumentSealer` calling a
 * Java or .NET service would implement this same interface, and no caller would
 * change.
 */
export interface DocumentSealer {
  seal(request: SealRequest): Promise<SealResult>;
}
